### ISSUE TITLE
GRpluginStands.txt - update stand coords and stand allocation for DW and define stands for NN and CK

### ISSUE THREAD

**Issue by simpson2** [VATeir/Ground-Radar-Plugin#1]
DW stand coordinates will be updated using the relevant IAA chart and stand allocation will be updated using the 'Spring 2020 Stand Allocation' doc. 
NN and CK stands will be defined using the relevant IAA charts. Perhaps then stand allocation will be implemented for CK and NN provided I have data.

**Comment by Fechulo** [comment]
@simpson2 I was given these by different peoples, not sure how accurate they are but it could help for the CK/NN stand allocation:

EINN:
9 = Business (Overnight), US Gov
11A, 11B, 11C = Remote stand US Gov, NOAA
21,22 = Remote Business (Gas & Go)
23-25 = Cargo 
26A,26B,27 = Ryanair
28-34 = Aer Lingus, Stobart
32-37 = American, Delta
39-43 = Omni, US Gov requiring docking

EICK:
2 - 5 - STK
6 - 11 - EIN/RYR/Other charter/scheduled carriers
12 - 20 - Cargo/Diversions

**Comment by simpson2** [comment]
> @simpson2 I was given these by different peoples, not sure how accurate they are but it could help for the CK/NN stand allocation:
> 
> EINN:
> 9 = Business (Overnight), US Gov
> 11A, 11B, 11C = Remote stand US Gov, NOAA
> 21,22 = Remote Business (Gas & Go)
> 23-25 = Cargo
> 26A,26B,27 = Ryanair
> 28-34 = Aer Lingus, Stobart
> 32-37 = American, Delta
> 39-43 = Omni, US Gov requiring docking
> 
> EICK:
> 2 - 5 - STK
> 6 - 11 - EIN/RYR/Other charter/scheduled carriers
> 12 - 20 - Cargo/Diversions

Thank you veeeeeeery much @Fechulo I shall check with Paul and the other staff.

**Comment by Paulmc98** [comment]
Fairplay Federico.

I have very basic knowledge on Cork and Shannon with regards stand allocation. Rian would be your go to for Shannon and Cork I am not sure but I am sure there will be someone to verify the allocations Federico has posted.
