### ISSUE TITLE
GRpluginMaps.txt - Implement support for dual-runway ops

### ISSUE THREAD

**Issue by simpson2** [VATeir/Ground-Radar-Plugin#2]
Seems possible to have both runways active with the chevron cover because each map can have more than one 'ACTIVE' line defined. Though need to make sure I am able to have taxiway B2 closed and A open while dual-ops active (currently A and B2 show closed while dual-ops active), as well as the correct stop bars displayed.

**Comment by simpson2** [comment]
Viability for this is **not looking good**. Unless I can't think of a viable solution, I don't think this can be done unless the developer implements the opposite of `ACTIVE`.

Two solutions were attempted:
  1) Define a new `ACTIVE` line for when DEP and ARR 28L and DEP 34, however, the problem of removing the 16/28L stop bar and having B2 closed and A open under the above conditions proved challenging.
  2) Copy the 28L and 34 maps with removing the 16/28L stop bar and TWY A closure and making B2 closed and `ACTIVE` when DEP and ARR 28L and DEP 34. This did not work with the problem I suspect is the way GRP parses the `ACTIVE` line perhaps overriding the former `ACTIVE` lines it seems or the latter ones. Not really sure.

One last solution I can think of is creating a new GRpluginMaps.txt file for just dual ops however this means people will have to back up the current file, drop the new one in for dual ops and then replace the current one again when dual ops are not in effect. This is clearly clunky and very much a 'bad' solution.

**Comment by Paulmc98** [comment]
I think for the amount of time Dual Ops is in operation, it is more hassle than worth making this work.

Making two Maps.txt files I think we should stay away from. I know we do this with TopSky but just for dual ops I think would be a waste of time and an unnecessary reason to make its use more complicated.

I think what we could just do is, show people how to activate/deactivate the maps manually.

**Comment by simpson2** [comment]
Agreed! With the renaming of the maps I think it will be trivial to teach how to deactivate/activate the required maps. Thank @Paulmc98!

**Comment by simpson2** [comment]
Closing the issue for now.
